# Generated by Django 2.0.1 on 2018-01-13 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secao_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 17, 11, 20, 215859), null=None)),
                ('data_devolucao', models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 17, 11, 20, 215882), null=None)),
                ('fk_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secao_admin.Funcionario')),
                ('fk_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secao_admin.Veiculo')),
            ],
        ),
        migrations.RemoveField(
            model_name='historico',
            name='data_entrega',
        ),
        migrations.AddField(
            model_name='historico',
            name='data_devolucao',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 17, 11, 20, 216333), null=None),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_reserva',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 17, 11, 20, 216314), null=None),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Funcionario',
            field=models.ManyToManyField(through='secao_admin.Reservas', to='secao_admin.Funcionario'),
        ),
    ]
