# Generated by Django 2.0.1 on 2018-01-13 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_admin', '0002_auto_20180113_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='Funcionario',
            new_name='funcionario',
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_devolucao',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 19, 11, 5, 66448), null=None),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_reserva',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 19, 11, 5, 66429), null=None),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_devolucao',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 19, 11, 5, 65960), null=None),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 19, 11, 5, 65934), null=None),
        ),
    ]
