# Generated by Django 2.0.1 on 2018-01-13 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_admin', '0003_auto_20180113_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='veiculo',
            field=models.ManyToManyField(through='secao_admin.Reservas', to='secao_admin.Veiculo'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_devolucao',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 20, 13, 30, 734229), null=None),
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_reserva',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 20, 13, 30, 734210), null=None),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_devolucao',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 20, 13, 30, 733798), null=None),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2018, 1, 13, 20, 13, 30, 733775), null=None),
        ),
    ]
